---
# babe key
- name: check if babe key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ babe_json }}"
  register: babe_key

- name: add babe key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ babe_json }}') }}"
  register: babe_insertion
  until: babe_insertion.status == 200
  retries: 3
  delay: 5
  when: babe_key.stat.exists

- name: show babe response
  debug:
    var: babe_insertion

# gran key
- name: check if gran key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ gran_json }}"
  register: gran_key

- name: add gran key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ gran_json }}') }}"
  register: gran_insertion
  until: gran_insertion.status == 200
  retries: 3
  delay: 5
  when: gran_key.stat.exists

- name: show gran response
  debug:
    var: gran_insertion

# imon key
- name: check if imon key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ imon_json }}"
  register: imon_key

- name: add imon key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ imon_json }}') }}"
  register: imon_insertion
  until: imon_insertion.status == 200
  retries: 3
  delay: 5
  when: imon_key.stat.exists

- name: show imon response
  debug:
    var: imon_insertion

# beef key
- name: check if beef key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ beef_json }}"
  register: beef_key

- name: add beef key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ beef_json }}') }}"
  register: beef_insertion
  until: beef_insertion.status == 200
  retries: 3
  delay: 5
  when: beef_key.stat.exists

- name: show beef response
  debug:
    var: beef_insertion

# octo key
- name: check if octo key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ octo_json }}"
  register: octo_key

- name: add octo key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ octo_json }}') }}"
  register: octo_insertion
  until: octo_insertion.status == 200
  retries: 3
  delay: 5
  when: octo_key.stat.exists

- name: show octo response
  debug:
    var: octo_insertion

# restart docker
- name: Restart services
  community.docker.docker_compose:
    project_src: '{{ ansible_env.HOME }}/seashell'
    build: no
    restarted: yes
  register: output
  # octo key exists & insert to keystore
  when: octo_key.stat.exists and octo_insertion.status == 200

- ansible.builtin.debug:
    var: output
