---
# aura key
- name: check if aura key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ aura_json }}"
  register: aura_key

- name: add aura key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ aura_json }}') }}"
  register: aura_insertion
  until: aura_insertion.status == 200
  retries: 3
  delay: 5
  when: aura_key.stat.exists

- name: show aura response
  debug:
    var: aura_insertion

# gran key
- name: check if gran key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ gran_json }}"
  register: gran_key

- name: add gran key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ gran_json }}') }}"
  register: gran_insertion
  until: gran_insertion.status == 200
  retries: 3
  delay: 5
  when: gran_key.stat.exists

- name: show gran response
  debug:
    var: gran_insertion

# octo key
- name: check if octo key exists
  local_action: stat path="{{ hostvars[inventory_hostname].key_root_path }}/{{ octo_json }}"
  register: octo_key

- name: add octo key to keystore
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: "{{ lookup('file','{{ hostvars[inventory_hostname].key_root_path }}/{{ octo_json }}') }}"
  register: octo_insertion
  until: octo_insertion.status == 200
  retries: 3
  delay: 5
  when: octo_key.stat.exists

- name: show octo response
  debug:
    var: octo_insertion

# restart docker
- name: Restart services
  community.docker.docker_compose:
    project_src: '{{ ansible_env.HOME }}/seashell'
    build: no
    restarted: yes
  register: output
  # gran key exists & insert to keystore
  when: gran_key.stat.exists and gran_insertion.status == 200

- ansible.builtin.debug:
    var: output
