
- name: checkout
  git:
    repo: '{{ git_repo }}'
    dest: '{{ node_home }}'
    version: '{{ git_version }}'
  tags:
    - build-chain
    - rebuild-chain

- name: compile
  command:
    cmd: '{{ cargo_bin }} +nightly build --release'
    chdir: '{{ node_home }}'
  async: 3600
  poll: 0
  register: node
  tags:
    - build-chain
    - rebuild-chain

- name: compile - check async status
  async_status: jid={{ node.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 1000
  delay: 10
  tags:
    - build-chain
    - rebuild-chain

# - name: change bin owner
#   file:
#     path: '{{ node_bin }}'
#     owner: '{{ user }}'
#     group: '{{ group }}'
#     mode: '0744'
#     state: file
#   become: true
#   tags:
#     - build-chain

- name: copy bin
  ansible.builtin.copy:
    src: '{{ node_bin }}'
    dest: '{{ user_bin }}'
    remote_src: yes
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0744'
  become: true
  tags:
    - build-chain
