
- name: copy chain spec
  ansible.builtin.copy:
    src: 'chainSpec.json'
    dest: '{{ user_home }}/chainSpec.json'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0744'
  become: true
  tags:
    - build-chain

- name: install systemd unit file
  template: src=node.j2 dest=/etc/systemd/system/node.service
  become: true
  vars:
    peers: [] # "{{ vars.bootnodes }}"
  tags:
    node-service

# - name: start validator node
#   systemd: state=started name=node daemon_reload=yes
#   become: true
#   tags:
#     node-service
